language: node_js

node_js:
  - "node"
  - "8"

env:
  global:
    - CC_TEST_REPORTER=cbd83e4586a5dcac1a62fd19ce78c9b367ce40f6c6970517afe03f14ac0bc18b"

before_install:
  - psql -c 'create database fastfoodfast;' -U postgres

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:client

after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


